apiVersion: batch/v1
kind: Job
metadata:
  name: tap-operator-sleep
  namespace: tap-operator
  labels:
    app.kubernetes.io/name: tap-operator
    app.kubernetes.io/part-of: tap-operator-sleep
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 1800
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      serviceAccount: tap-operator
      containers:
        - name: tap-operator
          image: tap-operator-sleep
          securityContext:
            runAsUser: 1000
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
  - image: tap-operator-sleep
    path: sleep
destinations:
  - image: tap-operator-sleep
    newImage: ghcr.io/bmoussaud/tap-operator
