apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretexports.secretgen.carvel.dev
spec:
  conversion:
    strategy: None
  group: secretgen.carvel.dev
  names:
    kind: SecretExport
    listKind: SecretExportList
    plural: secretexports
    singular: secretexport
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Friendly description
          jsonPath: .status.friendlyDescription
          name: Description
          type: string
        - description: Time since creation
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              properties:
                dangerousToNamespacesSelector:
                  items:
                    properties:
                      key:
                        description:
                          Property to target the resource for the match.
                          It supports dot notation.
                        type: string
                      operator:
                        description: Type of comparison.
                        enum:
                          - In
                          - NotIn
                          - Exists
                          - DoesNotExist
                        type: string
                      values:
                        description:
                          Values to match on the resource key using the comparison
                          operator.
                        items:
                          type: string
                        type: array
                    required:
                      - key
                      - operator
                    type: object
                  type: array
                toNamespace:
                  type: string
                toNamespaces:
                  items:
                    type: string
                  type: array
              type: object
            status:
              properties:
                conditions:
                  items:
                    properties:
                      message:
                        description:
                          Human-readable message indicating details about
                          last transition.
                        type: string
                      reason:
                        description:
                          Unique, this should be a short, machine understandable
                          string that gives the reason for condition's last transition.
                          If it reports "ResizeStarted" that means the underlying persistent
                          volume is being resized.
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    type: object
                  type: array
                friendlyDescription:
                  type: string
                observedGeneration:
                  format: int64
                  type: integer
                observedSecretResourceVersion:
                  type: string
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: SecretExport
    listKind: SecretExportList
    plural: secretexports
    singular: secretexport
  conditions:
    - lastTransitionTime: "2023-12-05T14:04:13Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2023-12-05T14:04:13Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1alpha1
