name: tap-operator-copy-packages CI
env:
  IMAGE_NAME: tap-operator-copy-packages
  REGISTRY: ghcr.io
on:
  push:
  #  tags:
  #    - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: initialize carvel tools
        uses: carvel-dev/setup-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          imgpkg version
          kbld version
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: copy-packages
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
